config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 
  
  get "users/index"
  get "products/index"
  get "agents/index"
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options'
  get '/set_setting_carriers' => 'distributors#set_setting_carriers'
    
  get '/agent' => 'home#portal' 
  post 'home/create_portal_order'
  get '/customer_login' => 'home#customer_login' 
  
  get '/set_shipping_values' => 'home#set_shipping_values'
  get '/get_shipping' => 'home#get_shipping' 
  
  post "home/login"

  get '/get_total_price' => 'distributors#get_total_price' 
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thankyou'
  post '/after_payment' => 'home#after_payment'
  post '/save_forum' => 'home#save_forum'
  get '/after_payment' => 'home#after_payment'
  post '/thankyou' => 'home#thankyou'
  post '/create_order' => 'orders#create_order'
  post '/create_agent_order' => 'orders#create_agent_order'
  get '/buy_now' =>"home#buy_now"
  get '/get_agent_form' => "home#get_agent_form"
  post '/after_payment_page' => 'home#after_payment_page'  
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/buy_upsell'=> 'orders#buy_upsell'
  get '/next_upsell'=> 'orders#next_upsell' 
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/add_product_to_cart' => 'home#add_product_to_cart'
  get '/clear_all' => 'home#clear_all'
  
  
  get '/fibre_hold' => 'home#fibre_hold'
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'
  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  get '/show_hide_billing_details' => 'home#show_hide_billing_details'
  post 'users/update_card_details'
  post 'users/logout'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end 

  
  resources :distributors, only: [:new, :create] do
    collection do 
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    resources :country_prices do
      collection do
        post :update_price
      end
    end
    
    resources :agents do 
      collection do 
        get 'get_orders'
        get 'get_orders_xls'
      end
    end 
    
    resources :coupons do 
      collection do 
        get :logout
      end 
    end
     
    get "/" => "orders#index"
    
    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end 
    
    resources :forums do
    end   
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :products
      
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
        get :set_price
        post :update_price
      end
      collection do 
        
      end
    end
    
    resources :users
    resources :orders, except: [:destroy]  do
      member do
        put :refund 
        get 'send_invoice'
        get 'release_order'
      end
      collection do
        
        get :refund
        get 'get_orders'
        get 'get_refund' 
        get 'get_refundable_orders'
        get 'change_date'
        get 'update_date'
        get 'update_customer_price'
        get 'update_days_gap'
        get "show_price"
        get "update_price"
        get "cancel_order"
        get "cancel1_order"
        get "cancel_order2"
        get :pull_details_from_shopify 
        get :distributor_orders
        get 'club_orders'
        get 'cancel_orders'
        get 'filter_orders'
        get 'get_orders'
      end
    end

    resources :shipments, except: [:destroy] 
    
    resources :subscribers do
      collection do
        get "download_contacts_csv"
      end
    end
    
  end
end

app/models/agent.rb
class Agent < ActiveRecord::Base

  has_many :orders, as: :orderer, dependent: :destroy
  validates :name, presence: true 
end

app/controllers/admin/agents_controller.rb
class Admin::AgentsController < Admin::ApplicationController  
  before_action :find_agent, only: [:edit, :update, :destroy, :get_orders]
  
  def index
    @agents = Agent.all.order("created_at desc").page(params[:page]).per_page(10) 
  end
  
  def new
    @agent = Agent.new
  end
  
  def create
    @agent = Agent.new(agents_params)

    if @agent.save
      redirect_to '/admin/agents', notice: 'Agent was successfully created.'
    else
      render action: 'new'
    end
  end
  
  def get_orders
    @orders = Order.where("agent_id =?",@agent.id)#.page(params[:page]).per_page(10) 
  end
  
  def get_orders_xls
    @agent = nil
    if params[:agent_id].to_i > 0 
      @agent = Agent.find params[:agent_id]
      @orders = Order.where(:agent_id=>params[:agent_id])
    else
      @orders = Order.where("agent_id is not null")
    end 
    render :pdf => "agent_orders", :layout => 'pdf.html.erb'   
  end

  def update
    if @agent.update(agent_params)
       redirect_to '/admin/agents', notice: 'Agent was successfully updated.'
    else
      render action: 'edit'
    end    
  end
  
  def destroy
    @agent.destroy
    redirect_to admin_agents_url, notice: 'Agent was successfully destroyed.'    
  end  
  
  private 
  
  def find_agent
    @agent = Agent.find params[:id]
  end 

  def agents_params
    params.require(:agent).permit(:name,:email)
  end
      
end

app/helpers/admin/agents_helper.rb
module Admin::AgentsHelper
  
  def get_product_names(order)
    order_items = order.order_items
    name = ""
    order_items.each do |o_i|
      if name == ""
        name = o_i.product.description
      else
        name += ", "+o_i.product.description
      end
    end
    return name
  end
  
  def get_start_date_value
    
    if params[:search]
      if params[:search][:start_date] 
        return params[:search][:start_date].to_date.strftime('%d/%m/%Y') 
      end
    end
    return DateTime.now.to_date.strftime('%d/%m/%Y')
  end

  def end_date_value
    if params[:search]
      if params[:search][:end_date]
        return params[:search][:end_date].to_date.strftime('%d/%m/%Y') rescue DateTime.now.to_date.strftime('%d/%m/%Y')
      end
    end
    return DateTime.now.to_date.strftime('%d/%m/%Y')
  end
  
  def get_order_type
    if params[:search]
      if params[:search][:order_type]
        return params[:search][:order_type] rescue ''
      end
    end
    return ''
  end
  
  def get_order_status
    if params[:search]
      if params[:search][:status]
        return params[:search][:status] rescue ''
      end
    end
    return ''
  end
  
  def get_first_name_value
    if params[:search]
      if params[:search][:first_name]
        return params[:search][:first_name] rescue ''
      end
    end
    return ''
  end
  
  def get_last_name_value
    if params[:search]
      if params[:search][:last_name]
        return params[:search][:last_name] rescue ''
      end
    end
    return ''
  end

  def get_email_value
    if params[:search]
      if params[:search][:email]
        return params[:search][:email] rescue ''
      end
    end
    return ''
  end
  
  def get_price(order_id)
    order = Order.find order_id 
    unless order.shopify_order_id.blank?  
      shop_url = "https://a98b179d72117d149e44ae83796e4c64:b62b5da657f75898e1d45eb6a6e0e247@hair-illusion-llc.myshopify.com/admin"
      ShopifyAPI::Base.site = shop_url   
      begin
        order = ShopifyAPI::Order.find(order.shopify_order_id)  
        return "#{order.total_price} -shopify"
      rescue
        return "cant refund"
      end
    end
    begin
      return (order.stripe_charge[:amount]/100.00).to_f 
    rescue
      return "no charge found in stripe"
    end
    
  end
   
end

app/views/admin/agents/_form.html.erb
<style>
	.add_table td {
		padding: 3px
	}
</style>

<%= form_for @agent, url: @agent.new_record? ? admin_agents_path : admin_agent_path(@agent), html: { class: 'form-horizontal' } do |f| %>

<% if @agent.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@agent.errors.count, "error") %> prohibited this admin_domain_distributor from being saved:</h2>

	<ul>
		<% @agent.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<table class="add_table">
	<tr>
		<td><b>Name:</b></td>
		<td> <%= f.text_field :name, :required=>true %> </td>
	</tr>
	<tr>
		<td><b>Company:</b></td>
		<td> <%= f.email_field :email, :required=>true %> </td> 
	</tr> 
</table>

<br />
<div class="actions">
	<%= f.submit "Save", :class=>"btn btn-primary" %>
	<%= link_to 'Back', admin_agents_path, :class=>"btn btn-default" %>
</div>
<br />
<br />
<br />
<% end %>

app/views/admin/agents/edit.html.erb
<h4>Editing Agent</h4>

<%= render 'form' %> 

app/views/admin/agents/get_orders.html.erb
<h3>Orders of <%= @agent.name %></h3>

<% if @orders.size > 0 %>
	<%= link_to "Download Orders", get_orders_xls_admin_agents_url(:agent_id=>@agent.id) %>
<%end%>

<table class="table table-striped table-bordered table-hover table-condensed grid-table">
  <thead>
    <tr> 
      <th>Created Date</th>
      <th>Customer</th>  
      <th>details</th> 
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr> 
        <td><%= order.created_at.strftime("%d/%m/%Y at %H:%M") %></td>
        <td><%= link_to("#{order.try(:orderer).try(:first_name)} #{order.try(:orderer).try(:last_name)}", admin_customer_path(order.try(:orderer))) %></td>  
        <td>
        	<%= link_to icon_text('Detail', 'glyphicon glyphicon-info-sign'), admin_order_path(order), class: 'btn btn-sm btn-success' %>
        </td>   
      </tr>
    <% end %>
  </tbody>
</table> 
<br>   

app/views/admin/agents/get_orders_xls.html.erb
<% if @agent %>
<h4> Agent Name: <%= @agent.name%></h4>
<%end%>
 
<br />
<br />

<table border="1" bordercolor="#ccc">
	<tr>
		<th>Date</th>
		<th>Customer</th>
		<th>Order Type</th>
		<th>Products</th> 
		<th>Product Price</th>
		<th>Shipping/Handling Fee</th>
		<th>Total Price</th>
	</tr>
	<% @orders.each do |order| %> 
		<tr>
			<td style="padding:5px"> <%= order.created_at.strftime("%d/%m/%Y at %H:%M") %> </td>
			<td style="padding:5px"> <%= order.try(:orderer).try(:name) %> </td>
			<% if order.try(:order_type) == "recurrent" %>
				<td> Recurrent</td>
			<% else %>
				<td> One Time</td>
			<%end%>
			<td> <%= get_product_names(order)%></td>
			<td>$<%= number_with_precision(order.total, :precision => 2) %></td> 
			<td>$<%= number_with_precision((order.shipping_price+order.process_handling_price), :precision => 2) %></td> 
			<td>$<%= number_with_precision((order.total+order.shipping_price+order.process_handling_price), :precision => 2) %></td>  
		</tr>	 
	<%end%>
</table>

app/views/admin/agents/index.html.erb
<h3>Agents</h3>

<%= link_to "Download All Agent Orders", get_orders_xls_admin_agents_url(:agent_id=>"all") %>

<table class="table table-striped table-bordered table-hover table-condensed grid-table">
  <thead>
    <tr> 
      <th>Name</th>
      <th>Email</th> 
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr> 
        <td><%= agent.name %></td>
        <td><%= agent.email %></td>  
         <td><%= link_to 'orders', get_orders_admin_agents_url(:id=>agent.id) %></td>
        <td><%= link_to 'Edit', edit_admin_agent_path(agent) %></td>
        <td><%= link_to 'Destroy', admin_agent_path(agent), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> 
<br> 
<%= link_to 'New Agent', new_admin_agent_path, :class=>"btn btn-primary" %>
<br />
<div class="pagination-center">
	<%= will_paginate @agents  %>
</div>

app/views/admin/agents/new.html.erb
<h4>New domain Agent</h4>

<%= render 'form' %> 