config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 
  
  get "users/index"
  get "products/index"
  get "agents/index"
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options'
  get '/set_setting_carriers' => 'distributors#set_setting_carriers'
    
  get '/agent' => 'home#portal' 
  post 'home/create_portal_order'
  get '/customer_login' => 'home#customer_login' 
  
  get '/set_shipping_values' => 'home#set_shipping_values'
  get '/get_shipping' => 'home#get_shipping' 
  
  post "home/login"

  get '/get_total_price' => 'distributors#get_total_price' 
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thankyou'
  post '/after_payment' => 'home#after_payment'
  post '/save_forum' => 'home#save_forum'
  get '/after_payment' => 'home#after_payment'
  post '/thankyou' => 'home#thankyou'
  post '/create_order' => 'orders#create_order'
  post '/create_agent_order' => 'orders#create_agent_order'
  get '/buy_now' =>"home#buy_now"
  get '/get_agent_form' => "home#get_agent_form"
  post '/after_payment_page' => 'home#after_payment_page'  
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/buy_upsell'=> 'orders#buy_upsell'
  get '/next_upsell'=> 'orders#next_upsell' 
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/add_product_to_cart' => 'home#add_product_to_cart'
  get '/clear_all' => 'home#clear_all'
  
  
  get '/fibre_hold' => 'home#fibre_hold'
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'
  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  get '/show_hide_billing_details' => 'home#show_hide_billing_details'
  post 'users/update_card_details'
  post 'users/logout'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end 

  
  resources :distributors, only: [:new, :create] do
    collection do 
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    resources :country_prices do
      collection do
        post :update_price
      end
    end
    
    resources :agents do 
      collection do 
        get 'get_orders'
        get 'get_orders_xls'
      end
    end 
    
    resources :coupons do 
      collection do 
        get :logout
      end 
    end
     
    get "/" => "orders#index"
    
    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end 
    
    resources :forums do
    end   
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :products
      
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
        get :set_price
        post :update_price
      end
      collection do 
        
      end
    end
    
    resources :users
    resources :orders, except: [:destroy]  do
      member do
        put :refund 
        get 'send_invoice'
        get 'release_order'
      end
      collection do
        
        get :refund
        get 'get_orders'
        get 'get_refund' 
        get 'get_refundable_orders'
        get 'change_date'
        get 'update_date'
        get 'update_customer_price'
        get 'update_days_gap'
        get "show_price"
        get "update_price"
        get "cancel_order"
        get "cancel1_order"
        get "cancel_order2"
        get :pull_details_from_shopify 
        get :distributor_orders
        get 'club_orders'
        get 'cancel_orders'
        get 'filter_orders'
        get 'get_orders'
      end
    end

    resources :shipments, except: [:destroy] 
    
    resources :subscribers do
      collection do
        get "download_contacts_csv"
      end
    end
    
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  respond_to :html, except: [:shipping]
  respond_to :js, only: [:index]
    
  
  def distributor_orders
    distributor_ids = Distributor.all.collect(&:id) 
    @orders = Order.where("orderer_id in (?) and orderer_type='Distributor'",distributor_ids).order("DATE(created_at) DESC").page(params[:page]).per_page(10) 
  end
  
  def get_refund
    @orders = []
  end

  def release_order
    @order = Order.find(params[:id]) 
    @order.held = false
    @order.save 
    redirect_to :back
  end
   
  def send_invoice
    @order = Order.find(params[:id]) 
    OrderMailer.order_receipt(@order.id).deliver! 
    redirect_to :back, :notice=>"Invoice sent to customer"
  end
  
  def get_refundable_orders
    first_name = (params[:search][:first_name].present? && params[:search][:first_name]!='') ? params[:search][:first_name].to_s : params[:search][:first_name]
    last_name = (params[:search][:last_name].present? && params[:search][:last_name]!='') ? params[:search][:last_name].to_s : params[:search][:last_name]
    
    email = (params[:search][:email].present? && params[:search][:email]!='') ? params[:search][:email].to_s : params[:search][:email]
 

    query = "select o.id as order_id, o.refunded_at as refunded_at, o.shopify_order_id as shopify_order_id, o.created_at as created_at,c.first_name as first_name, c.last_name as last_name, c.email as email_id, o.last_delivery_date as last_date from orders o 
          left join customers c on o.orderer_id = c.id where "
          
          query += " c.first_name LIKE '%#{first_name}%' and " unless first_name.blank? 
          query += " c.last_name LIKE '%#{last_name}%' and " unless last_name.blank? 
          query += " c.email LIKE '%#{email}%' and " unless email.blank?
          
          query +=" o.cancelled=false and ( o.stripe_id is not null or shopify_order_id is not null) and refunded_at is null order by created_at desc"


          @orders = Order.find_by_sql query    
  end
   
  def club_orders
    @orders = []
    @total_active_orders = Order.where("order_type = 'recurrent' and cancelled = false").size
  end
  
  def change_date
    @return_url = request.referer
    @order = Order.find params[:id]
  end
  
  def update_customer_price
    customer = Customer.find params[:customer_id]
    @error = ""
    if customer.update_attribute(:price, params[:price].to_f)
       @error = "saved"  
    end 
  end
  
  def update_date
    @order = Order.find params[:order_id]
    @error = ""
    if @order.update_attribute(:next_delivery_date, params[:order][:next_delivery_date])
       @error = "saved" 
    end 
    
  end
  
  def cancel_orders
    @orders = []
  end
  
  def update_days_gap
    @order = Order.find params[:order_id]
    @error = ""
    if @order.update_attribute(:gap_days, params[:order][:gap_days])
       @error = "saved" 
    end 
    if @order.last_delivery_date
      @order.next_delivery_date = @order.last_delivery_date + params[:order][:gap_days].to_i.days
    else
      @order.next_delivery_date = Date.today + params[:order][:gap_days].to_i.days
    end 
    @order.save
  end
  
  def get_orders
    first_name = (params[:search][:first_name].present? && params[:search][:first_name]!='') ? params[:search][:first_name].to_s : params[:search][:first_name]
    last_name = (params[:search][:last_name].present? && params[:search][:last_name]!='') ? params[:search][:last_name].to_s : params[:search][:last_name]
    
    email = (params[:search][:email].present? && params[:search][:email]!='') ? params[:search][:email].to_s : params[:search][:email]
    
    
    query = "select o.id as order_id, o.created_at as created_at,c.first_name as first_name, c.last_name as last_name, c.email as email_id, o.last_delivery_date as last_date from orders o 
          left join customers c on o.orderer_id = c.id where "
          
          query += " c.first_name LIKE '%#{first_name}%' and " unless first_name.blank? 
          query += " c.last_name LIKE '%#{last_name}%' and " unless last_name.blank? 
          query += " c.email LIKE '%#{email}%' and " unless email.blank?
          
          query +=" (o.cancelled=false and parent_order_id is null and order_type='recurrent')  order by o.id desc"

          @orders = Order.find_by_sql query
  end 
  
  def filter_orders
    @total_active_orders = Order.where("order_type = 'recurrent' and cancelled = false").size
    @orders = []
    orders = Order.where("version_2_order = true and order_type = 'recurrent' and parent_order_id is null") 
    
    first_name = (params[:search][:first_name].present? && params[:search][:first_name]!='') ? params[:search][:first_name].to_s : params[:search][:first_name]
    last_name = (params[:search][:last_name].present? && params[:search][:last_name]!='') ? params[:search][:last_name].to_s : params[:search][:last_name]
    
    email = (params[:search][:email].present? && params[:search][:email]!='') ? params[:search][:email].to_s : params[:search][:email]
    
    
          query = "select o.* from orders o 
          left join customers c on o.orderer_id = c.id where " 
          query += " c.first_name LIKE '%#{first_name}%' and " unless first_name.blank? 
          query += " c.last_name LIKE '%#{last_name}%' and " unless last_name.blank? 
          query += " c.email LIKE '%#{email}%' and " unless email.blank?

          query +=" (o.cancelled=false and o.parent_order_id is null and o.order_type='recurrent')" 
 
          @orders = Order.find_by_sql query     
  end
  
  def index
    if params[:customer_id]
      @orderer = Customer.find(params[:customer_id])
    elsif params[:distributor_id]
      @orderer = Distributor.find(params[:distributor_id])
    end

    respond_to do |format|
      format.html {}
      format.js do
        if @orderer.present?
          @orders = @orderer.orders.where(:cancelled=>false, :paid=>true)
        else
          @orders = Order.where(:cancelled=>false, :paid=>true).includes(:orderer)
        end  
        @orders = @orders.order("id desc")
        grid_table_for(@orders, index_params)
      end
    end
  end

  def show
    @order = Order.find(params[:id])
  end
  
  def show_price
    
  end
  
  def cancel_order
    order = Order.find params[:order_id]
    if order
      order.cancelled = true
      order.cancelled_at = Time.now
      if order.save
        OrderMailer.order_cancel_confirmation(order.id).deliver! 
        OrderMailer.admin_cancel_notification(order.id).deliver! 
      end
    end 
  end

  def cancel1_order
    order = Order.find params[:order_id]
    if order
      order.cancelled = true
      order.cancelled_at = Time.now
      if order.save 
      end
    end 
  end

  def cancel_order2
    order = Order.find params[:order_id]
    if order
      order.cancelled = true
      order.cancelled_at = Time.now
      if order.save
        OrderMailer.order_cancel_confirmation(order.id).deliver! 
        OrderMailer.admin_cancel_notification(order.id).deliver! 
      end
    end 
  end
  
  def update_price
    
    price = ProductPrice.first
    if price
      price.update_attributes(:price=>params[:price].to_f, :recurrent_price=>params[:recurrent_price].to_f, :small_product_price=>params[:small_product_price].to_f, :shipping_price => params[:shipping_price].to_f, :combo2_price=>params[:combo2_price].to_f, :combo3_price=>params[:combo3_price].to_f)
    else
      ProductPrice.create(:price=>params[:price].to_f, :recurrent_price=>params[:recurrent_price].to_f, :small_product_price=>params[:small_product_price].to_f, :shipping_price => params[:shipping_price].to_f, :combo2_price=>params[:combo2_price].to_f, :combo3_price=>params[:combo3_price].to_f)
    end
    
    if(params[:price].to_f>0)
      products = Product.where(:product_type=>"normal").where("description in (?)", ['Jet Black','Black','Dark Brown','Brown','Light Brown','Auburn','Blonde', 'Light Blonde'])
      products.each do |p| 
        p.update_attribute(:price, params[:price].to_f*100)
      end
    end
    
    if(params[:small_product_price].to_f>0)
      products = Product.where(:product_type=>"normal").where("description in (?)", ['Jet Black 18g','Black 18g','Dark Brown 18g','Brown 18g','Light Brown 18g','Auburn 18g','Blonde 18g', 'Light Blonde 18g'])
      products.each do |p| 
        p.update_attribute(:price, params[:small_product_price].to_f*100)
      end
    end
    
    if(params[:valuepack2_price].to_f>0)
      product = Product.where(:description=>"Value Pack 2").first
      product.update_attribute(:price, params[:valuepack2_price].to_f*100) if product
    end
    
    if(params[:spray_combo_price].to_f>0) 
      ProductPrice.first.update_attribute(:spray_combo_price, params[:spray_combo_price].to_f*100)
    end 
    
    if(params[:valuepack2_shipping_price].to_f>0)
      product = Product.where(:description=>"Value Pack 2").first
      product.update_attribute(:shipping_price, params[:valuepack2_shipping_price].to_f*100) if product
    end
    
    if(params[:valuepack3_shipping_price].to_f>0)
      product = Product.where(:description=>"Value Pack 3").first
      product.update_attribute(:shipping_price, params[:valuepack3_shipping_price].to_f*100) if product
    end
    
    if(params[:valuepack4_shipping_price].to_f>0)
      product = Product.where(:description=>"Value Pack 4").first
      product.update_attribute(:shipping_price, params[:valuepack4_shipping_price].to_f*100) if product
    end
    
    if(params[:valuepack5_shipping_price].to_f>0)
      product = Product.where(:description=>"Value Pack 5").first
      product.update_attribute(:shipping_price, params[:valuepack5_shipping_price].to_f*100) if product
    end
    
    if(params[:combo_shipping_price].to_f>0)
      product = Product.where(:description=>"Combo Pack").first
      product.update_attribute(:shipping_price, params[:combo_shipping_price].to_f*100) if product
    end 
    
    if(params[:valuepack3_price].to_f>0)

app/views/admin/orders/_customer_form.html.erb
<div id="checkoutForm" class="row">
  <div class="col-md-6">
    <h2>Order Form</h2>

    <%= form_for @order, url: @customer.new_record? ? admin_orders_path : admin_customer_orders_path(@customer), html: { class: 'form-horizontal' } do |f| %>
      <%= f.fields_for :order_items, @order_item do |oi| %>
        <%= control_group(@order_item, :color, label: 'Select Color') do %>
		<%= oi.select( "product_id", options_from_collection_for_select(Product.where("product_type='normal'"), "id", "description", @order.order_items[0].product_id), {:include_blank => false}, { :class=>"form-control required"})%>  
        <% end %>

        <%= control_group(@order_item, :color, label: 'Quantity') do %>
          <%= oi.number_field :quantity, min: 1, step: 1, class: 'form-control required order-quantity', data: { price: 59.95 } %></td>
        <% end %>
      <% end %>

      <div class="contact_info">
        <h4>PERSONAL INFORMATION</h4>
        <%= fields_for @customer do |c| %>
          <%= control_group(@customer, :first_name, label: 'First Name') do %>
            <%= c.text_field :first_name, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :last_name, label: 'Last Name') do %>
            <%= c.text_field :last_name, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :email, label: 'Email') do %>
            <%= c.email_field :email, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :address1, label: 'Street Address') do %>
            <%= c.text_field :address1, class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :address2, label: 'Suite / Apt') do %>
            <%= c.text_field :address2, class: 'form-control' %>
          <% end %>

          <%= control_group(@customer, :city, label: 'City') do %>
            <%= c.text_field :city, class: 'form-control required' %>
          <% end %>
			
		  <%= control_group(@customer, :country, label: 'Country') do %>
            <%= c.country_select :country, { prompt: 'Please select a country'}, { class: 'form-control required' } %>
          <% end %> 
          
          <%= control_group(@customer, :state, label: 'State/Region/Province') do %>
            <%= c.text_field :state,  class: 'form-control required' %>
          <% end %>

          <%= control_group(@customer, :zip, label: 'Postal/Zip Code') do %>
            <%= c.text_field :zip, class: 'form-control required'%>
          <% end %>
        <% end %>

      </div>
      <div class="payment">
        <h4>CREDIT CARD INFORMATION</h4>
        <%= fields_for @credit_card do |cc| %>
          <%= control_group(@credit_card, :name, label: 'Name on Card') do %>
            <%= cc.text_field :name, class: 'form-control required', autocomplete: :off %>
          <% end %>

          <%= control_group(@credit_card, :number, label: 'Card Number') do %>
            <%= cc.number_field :number, class: 'form-control required', autocomplete: :off, :size => 20 %>
          <% end %>

          <%= control_group(@credit_card, :cvc, label: 'CVC') do %>
            <%= cc.number_field :cvc, class: 'form-control required', autocomplete: :off, :size => 4 %>
          <% end %>

          <%= control_group(@credit_card, :exp_month, label: 'Expiration') do %>
            <div class="row">
              <div class="col-md-4">
                <%= select_month(nil, { :prefix => :credit_card, :field_name => :exp_month, use_month_numbers: true, prompt: 'MM' }, { class: 'form-control required' }) %>
              </div>
              <div class="col-md-8">
                <%= select_year(nil, { :prefix => :credit_card, :field_name => :exp_year, start_year: Time.now.year, end_year: Time.now.year + 10, prompt: 'YYYY' }, { class: 'form-control required' }) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="form-group">
        <div style="text-align:center;" class="col-md-12">
          <%= f.submit 'Create Order', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/orders/_orders_list.html.erb
<% if @orders.empty? %>
Sorry, no orders found, Please search changing the filter values..
<%else%>
<table class="table table-striped table-bordered table-hover table-condensed grid-table">
	<th> Customer Name </th>
	<th> Agent/Domain </th>
	<th> Status </th>
	<th> Started </th>
	<th> Last delivery </th>
	<th> Next Delivery </th>
	<th> Change Date </th>
	<th> Details </th> 
 
	<% @orders.each do |order| %> 
	<tr>
		<td>  
			<% if order.orderer %>
				<%= order.orderer.name %>
			<%end%> 
		</td> 
		<td> 
			<% if order.agent_id.nil? %>
				<%= order.host %>
			<% else%>
				<%= order.agent_id %>
			<%end%> 
		</td>
		<td> <% if order.cancelled %>
		Cancelled
		<% else%>
		Active
		<%end%> </td>
		<td> <% if order.first_delivery_date %>
		<%= order.first_delivery_date.strftime("%d/%m/%Y") %>
		<%end%> </td>
		<td> <% if order.last_delivery_date %>
		<%= order.last_delivery_date.strftime("%d/%m/%Y") %>
		<%end%> </td>
		<td> <% if order.next_delivery_date %>
		<%= order.next_delivery_date.strftime("%d/%m/%Y") %>
		<%end%> </td>
		<td> 
		<%= link_to "Change Delivery Date", change_date_admin_orders_path(:id=>order.id) %>
		</td>
		<td> <%= link_to("Details", admin_order_path(order)) %> </td>
	</tr>
	<%end%>
</table>
<%end%>

app/views/admin/orders/_row.html.erb
<tr>
  <td><%= order.created_at %></td>
  <td><%= order.id %></td>
  <td>
    <% if order.orderer_type == "Customer" %>
      <%= link_to("#{order.try(:orderer).try(:first_name)} #{order.try(:orderer).try(:last_name)}", admin_customer_path(order.try(:orderer))) %>
    <% elsif order.orderer_type == "Distributor" %>
      <%= link_to(order.orderer.company_name, admin_distributor_path(order.try(:orderer))) %>
    <% end %>
  </td>
  <td> 
  		<%= order.order_source %>  
  </td>
  <td>
    <% if order.shipment.present? %>
      <%= link_to(order.shipment.created_at, admin_shipment_path(order.try(:shipment))) %>
    <%elsif order.amazon_order_id.present?%>
    	<%= order.order_status %>
    <% end %>
  </td>
  <td>
    <%= link_to icon_text('Detail', 'glyphicon glyphicon-info-sign'), admin_order_path(order), class: 'btn btn-sm btn-success' %>
    <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_order_path(order), class: 'btn btn-sm btn-primary' %>
  </td>
</tr>

app/views/admin/orders/cancel1_order.js.erb
window.location.reload()

app/views/admin/orders/cancel_order.js.erb
window.location.reload()

app/views/admin/orders/cancel_order2.js.erb
$("#order_row_<%=params[:order_id]%>").remove();
alert("Order cancelled successfully");

app/views/admin/orders/club_orders.html.erb
<%= form_for :search, :url => { :controller=>'admin/orders', :action => 'filter_orders' }, html: {class: 'form form-horizontal', style:'margin:0px;left:0px;' }, :method => :get do |f|%>
<div class="well" style="width: 100%">  
	<b>
	Total Active Orders: <%= @total_active_orders %>
	</b>
	<br />
	<table align="center" class="quick_search_table" >
		<tr> 
 			<td class="report_td"> First Name: </td>
			<td style="width: 120px;padding-right:20px"> <%= f.text_field :first_name, :value => get_first_name_value, :style=>"width:150px" %> </td>
			<td class="report_td"> Or </td>
 			<td class="report_td"> Last Name: </td>
			<td style="width: 100px;padding-right:20px"> <%= f.text_field :last_name, :value => get_last_name_value, :style=>"width:150px" %> </td>
			<td class="report_td"> Or </td>
			<td class="report_td"> Email: </td>
			<td style="width: 100px;padding-right:20px"> <%= f.email_field :email, :value => get_email_value, :style=>"width:200px" %> </td>		
			<td class="report_td"> Status: </td>
			<td style="width: 100%;padding-left: 20px"> 
				<%= f.submit "Search", :class=>"btn btn-primary btn-sm", "data-disable-with"=>"Wait..." %> 
			</td style="width: 100%;padding-left: 50px">
		</tr>
	</table>
</div>
<%end%>  

<div id="ordersList">
	<%=render "orders_list" %>
</div> 

<script type="text/javascript"> 

  function onDowloadReport()
  {  
	params = "start_date="+$("#search_start_date").val()+"&end_date="+$("#search_end_date").val()+"&distributor_id="+$("#domain_distributor_id").val();		
	window.location.href = '<%=download_report_admin_domain_distributors_path%>'+"?"+params; 
  }
</script>

app/views/admin/orders/distributor_orders.html.erb
 
<%= will_paginate @orders, :container => false %>

<br />
<table class="table table-striped table-bordered table-hover table-condensed grid-table">
	<tr>
		<th>Date</th> 
		<th>Distributor</th>
		<th>Details</th>
	</tr>
	<% @orders.each do |order| %>
		<tr>
			<td>
				<%= order.created_at.strftime("%d/%m/%Y at %H:%M") %>
			</td>
			<td> 
				<%= link_to("#{order.try(:orderer).try(:name)}", admin_distributor_path(order.try(:orderer))) %>
 
			</td>
			<td>  
				<%= link_to("Order Details", admin_distributor_orders_path(order.try(:orderer))) %> 
			</td>
		</tr>
	<%end%>
</table> 

<%= will_paginate @orders, :container => false %>

app/views/admin/orders/get_refundable_orders.js.erb
$("#customerRefundOrderList").html("<%= escape_javascript(render(:partial => 'refund_orders_list')) %>");

app/views/admin/orders/new.html.erb
<% if @distributor.present? %>
  <%= render 'distributor_form' %>
<% else %>
  <%= render 'customer_form' %>
<% end %>

app/views/admin/orders/refund.js.erb
alert("<%= @error %>")
if( "<%= @error %>" == "Successfully refunded to customer")
{
	$("#order_row_<%=params[:id]%>").remove()
} 

app/views/admin/orders/update_customer_price.js.erb
<% if @error == "saved" %>
	alert("Updated the price successfully") 
<%else%>
	alert("Failed to update the price.")
<%end%>

app/views/admin/orders/update_date.js.erb
<% if @error == "saved" %>
	alert("Updated the next delivery date successfully")
	window.location.href = "<%= params[:return_url] %>"
<%else%>
	alert("Failed to update next delivery date.")
<%end%>

app/views/admin/orders/update_days_gap.js.erb
alert("updated successfully.")
window.location.reload();