config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 
  
  get "users/index"
  get "products/index"
  get "agents/index"
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options'
  get '/set_setting_carriers' => 'distributors#set_setting_carriers'
    
  get '/agent' => 'home#portal' 
  post 'home/create_portal_order'
  get '/customer_login' => 'home#customer_login' 
  
  get '/set_shipping_values' => 'home#set_shipping_values'
  get '/get_shipping' => 'home#get_shipping' 
  
  post "home/login"

  get '/get_total_price' => 'distributors#get_total_price' 
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thankyou'
  post '/after_payment' => 'home#after_payment'
  post '/save_forum' => 'home#save_forum'
  get '/after_payment' => 'home#after_payment'
  post '/thankyou' => 'home#thankyou'
  post '/create_order' => 'orders#create_order'
  post '/create_agent_order' => 'orders#create_agent_order'
  get '/buy_now' =>"home#buy_now"
  get '/get_agent_form' => "home#get_agent_form"
  post '/after_payment_page' => 'home#after_payment_page'  
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/buy_upsell'=> 'orders#buy_upsell'
  get '/next_upsell'=> 'orders#next_upsell' 
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/add_product_to_cart' => 'home#add_product_to_cart'
  get '/clear_all' => 'home#clear_all'
  
  
  get '/fibre_hold' => 'home#fibre_hold'
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'
  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  get '/show_hide_billing_details' => 'home#show_hide_billing_details'
  post 'users/update_card_details'
  post 'users/logout'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end 

  
  resources :distributors, only: [:new, :create] do
    collection do 
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    resources :country_prices do
      collection do
        post :update_price
      end
    end
    
    resources :agents do 
      collection do 
        get 'get_orders'
        get 'get_orders_xls'
      end
    end 
    
    resources :coupons do 
      collection do 
        get :logout
      end 
    end
     
    get "/" => "orders#index"
    
    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end 
    
    resources :forums do
    end   
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :products
      
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
        get :set_price
        post :update_price
      end
      collection do 
        
      end
    end
    
    resources :users
    resources :orders, except: [:destroy]  do
      member do
        put :refund 
        get 'send_invoice'
        get 'release_order'
      end
      collection do
        
        get :refund
        get 'get_orders'
        get 'get_refund' 
        get 'get_refundable_orders'
        get 'change_date'
        get 'update_date'
        get 'update_customer_price'
        get 'update_days_gap'
        get "show_price"
        get "update_price"
        get "cancel_order"
        get "cancel1_order"
        get "cancel_order2"
        get :pull_details_from_shopify 
        get :distributor_orders
        get 'club_orders'
        get 'cancel_orders'
        get 'filter_orders'
        get 'get_orders'
      end
    end

    resources :shipments, except: [:destroy] 
    
    resources :subscribers do
      collection do
        get "download_contacts_csv"
      end
    end
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery :except => [:thankyou]
  require 'shipwire'
  
    after_action :allow_iframe

  def allow_iframe
    response.headers.delete('X-Frame-Options')
  end
      
  def index       
 
    #session[:order_id] = nil
    #session[:card] = nil
    session[:shipping_price] = nil 
    session[:shipping_price] = nil
    session[:country_shipping_code] = nil
    
    session[:cart] = nil
    @orderer = Customer.new
    @order = @orderer.orders.build(order_items_attributes: [quantity: 1])
    @credit_card = CreditCard.new
    @distributor = Distributor.new     
    session[:product_cart] = nil
  end
  
  def clear_all
    session[:product_cart] = nil
    session[:cart] = nil
  end
  
  def customer_login
    
  end
  
  def login
    @error = ""
    if params[:customer][:email].blank? || params[:customer][:password].blank? 
      @error = "Please enter email/password"
    else
      customer = Customer.where(:email=>params[:customer][:email], :password=>params[:customer][:password]).first
      unless customer 
        @error = "Invalid credentials"
      else 
        session[:customer_id] = customer.id 
      end
    end 
  end
  
  def after_payment_page 
    
    if params[:payer_status] == "verified"
      order = Order.find params[:item_number]
      if order 
        order.paid = true         
        order.save 
        customer = Customer.find order.orderer_id
        customer.paypal = params[:payer_email]
        customer.save
        
        OrderMailer.order_receipt(order.id).deliver!  
        OrderMailer.admin_notification(order.id).deliver! 
      end
    end 
  end
  
  def get_shipping
    
    items = []
    address = {}
    @error = ''
    qty = 0
    
    amazon_items = []
    
    if session[:product_cart] && session[:product_cart][:products].size > 0   
      session[:product_cart][:products].each_with_index do |d,index| 
        qty +=d[:quantity].to_i 
        product = Product.where(:description=>d[:name],:product_type=>'normal').first
        if product
          items << { :sku =>  product.sku, :quantity => d[:quantity], :commercialInvoiceValue => d[:price].to_f*d[:quantity].to_f, :commercialInvoiceValueCurrency => 'USD'}
          
          amazon_items << { :SellerSKU =>  product.amazon_sku, :SellerFulfillmentOrderItemId => product.id.to_s, :Quantity => d[:quantity].to_i, :GiftMessage => 'Thank you for ordering hairillusion product'}
        end
      end
       
      if params[:billing_first_name].blank?
         name = params[:first_name] + " " + params[:last_name]
      else
        name = params[:billing_first_name] + " " + params[:billing_last_name]
      end
      
      if params[:billing_address1].blank?
        address1 = params[:address1]
        address2 = params[:address2]
        city = params[:city]
        state = params[:order_state]
        zip = params[:zip]
        country = params[:cb_country]
      else
        address1 = params[:billing_address1]
        address2 = params[:billing_address2]
        city = params[:billing_city]
        state = params[:billing_state]
        zip = params[:billing_zip]
        country = params[:billing_country]
      end
      
      
      if items.size > 0
        address    = { 
          :email    => params[:email],
          :name    => name,
          :company    => "",
          :address1    => address1,
          :address2    => address2,
          :address3    => "",
          :city        => city,
          :state       => state,
          :postalCode  => zip,
          :country    =>  country,
          :phone      => '', 
          :isCommercial    => 0, 
          :isPoBox    => 0
        } 
      end  
      
      if country == "US"  
        
        require "peddler" 
        client = MWS.fulfillment_outbound_shipment(
          primary_marketplace_id: "ATVPDKIKX0DER",
          merchant_id: "A1D4HR9FQLX93E",
          aws_access_key_id: "AKIAJSFSWTEXHLUC4IJQ",
          aws_secret_access_key: "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",
        )  
        amazon_address = {:Name=>name, :Line1=> address1, :Line2=> address2, :City=>city, :StateOrProvinceCode=> state, :PostalCode=>zip, :CountryCode=>'US'}
           
        begin
          result = client.get_fulfillment_preview(amazon_address, amazon_items, opts = {}).parse  
          if result["FulfillmentPreviews"]["member"]
            setup_amazon_carriers(result["FulfillmentPreviews"]["member"])
          else 
            setup_shipwire_carriers(items, address, qty)
          end  
        rescue
          @error = "Please make sure you have entered valid address"
        end
        
        if @carriers.size == 0
          @error = '' 
          begin
            setup_shipwire_carriers(items, address, qty) 
          rescue
            @error = "Please make sure you have entered valid address"
          end
        end
        
      else
        setup_shipwire_carriers(items, address, qty)
      end  
    end 
  end
  
  def set_shipping_values
    shipping_arr = params[:value].split("____")  
    session[:shipping_price] = shipping_arr[0].to_f
    shipping_code = shipping_arr[1]
    session[:country_shipping_code] = shipping_arr[1]  
  end
  
  def faq
  end

  def photos
  end
  
  def forgot_password
    
  end
  
  def forgot_password_email
    @errors = ""
    if params[:email] == ""
      @errors = "Please enter your valid distributor email id"
    else
      distributor = Distributor.where(:email=>params[:email]).first 
      if distributor
        OrderMailer.reset_email(distributor.id).deliver! 
      else
        @errors = "Please enter your valid distributor email id"
      end
    end
  end
  
  def password_reset_success
    
  end
  
  def show_hide_billing_details
    session[:shipping_price] = nil 
    session[:shipping_price] = nil
    session[:country_shipping_code] = nil    
  end
  
  def what_is_it
  end

  def how_it_works
  end

  def about_us
  end

  def color
  end

  def contact_us
  end

  def mens_hair_loss
  end

  def womens_hair_loss
  end

  def thankyou 
  end
  
  def buy_now
    session[:cart] = nil
  end
  
  def after_payment
    redirect_to thank_you_path
  end
  
  def forum 
    @forums = Forum.where(:approved=>true, :domain_name=>"hairillusion.com")#.paginate(per_page: 2, page: params[:page])  
  end
  
  def get_forums
    @forums = []
    if params[:search][:country].blank? && params[:country][:state].blank? 
      @forums = []#.paginate(per_page: 2, page: params[:page])
    elsif params[:search][:country].blank?
      @forums = Forum.where(:domain_name=>request.host,:approved=>true, :state=>params[:country][:state])#.paginate(per_page: 2, page: params[:page])
    elsif params[:country][:state].blank?  
      @forums = Forum.where(:domain_name=>request.host,:approved=>true, :country=>params[:search][:country]).paginate(per_page: 2, page: params[:page])#.paginate(per_page: 2, page: params[:page])
    else
      @forums = Forum.where(:domain_name=>request.host,:approved=>true, :country=>params[:search][:country], :state=>params[:country][:state])#.paginate(per_page: 2, page: params[:page])
    end
  end
  
  def new_forum
    @forum = Forum.new
  end
  
  def get_agent_form
    @agent = Agent.where("name = ?", params[:agent_id]).first   
    @agent = Agent.create(:name=>params[:agent_id]) unless @agent    
    
    session[:cart] = nil
    @orderer = Customer.new
    @order = @orderer.orders.build(order_items_attributes: [quantity: 1])
    @credit_card = CreditCard.new
    @distributor = Distributor.new     
    session[:product_cart] = nil
  end
  
  def save_forum
    @forum = Forum.new(admin_forum_params)
    @forum.state = params[:country][:state]
    @forum.domain_name = request.host
    if @forum.save 
      @forum.update_attribute(:approved,false) 
     # OrderMailer.send_forum_email(@forum.content).deliver!
      @forums = Forum.where(:approved=>true) 
      redirect_to forum_path, notice: 'Your forum request is successfully submitted.'
    else 
      render action: 'new_forum'
    end 
  end
  
  def get_states 
    
    shipping_price = session[:shipping_price] rescue "0" 
    
    cc= CountryPrice.where(:country_code=>params[:parent_region]).last   
    if cc 
      if shipping_price.to_f > 0
        @shipping = shipping_price
      else
        @shipping = session[:shipping_price] = cc.price
      end
      
      if !session[:product_cart].nil? && session[:product_cart][:type] != "recurrent" 
        if session[:product_cart][:products][0][:tax] != @shipping 
          session[:product_cart][:products][0][:tax] = @shipping
        end 
      end
    else
      price_row = ProductPrice.first
      if price_row
        if shipping_price.to_f > 0
          @shipping = shipping_price
        else
          @shipping = session[:shipping_price] = cc.price
        end
      else
        @shipping = 0
      end 
      if !session[:product_cart].nil? && session[:product_cart][:type] != "recurrent" 
        if session[:product_cart][:products][0][:tax] != @shipping 
          session[:product_cart][:products][0][:tax] = @shipping
        end 
      end
    end 
  end
  
  def add_to_cart 
    @url = 'http://hair-illusion-llc.myshopify.com/cart/'
    session[:cart] = Array.new if session[:cart].nil? 
    position = nil
    if session[:cart].size > 0  
      session[:cart].each_with_index do |d,index|
        if d[:name] == params[:product]
          position = index   
        end
      end
      unless position.nil?
        session[:cart][position][:quantity] = session[:cart][position][:quantity].to_i + params[:quantity].to_i
        if params[:product_type] == "upsell"
          session[:cart][position][:price] = session[:cart][position][:price].to_f + (19.95 * params[:quantity].to_i)
        else
          session[:cart][position][:price] = session[:cart][position][:price].to_f + (params[:unit_price].to_f * params[:quantity].to_i)
        end 

app/views/home/_bonus_products.html.erb
<div style="width: 291px">

	<div class="FormSubHeadlineL">
		Choose your color
	</div>
	<input type="hidden" id="productType">
	<input type="hidden" id="productQuantity"> 

	<div class="checkbox color" id="color-jetblack" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="JetBlack" name="Color" value="JET" onclick="setProductType('Jet Black')">
		<%= image_tag 'color-jet-black.png', :clas=>"colorimg"%>
		Jet Black
	</div>
	<div class="checkbox color" id="color-black" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="Black" name="Color" value="BLK" onclick="setProductType('Black')">
		<%= image_tag 'color-black.png', :clas=>"colorimg"%>
		Black
	</div>
	<div class="checkbox color" id="color-dkbrown" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="DarkBrown" name="Color" value="DKBR" onclick="setProductType('Dark Brown')">
		<%= image_tag 'color-dark-brown.png', :clas=>"colorimg"%>
		Dark Brown
	</div>
	<div class="checkbox color" id="color-brown" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="Brown" name="Color" value="BR" onclick="setProductType('Brown')">
		<%= image_tag 'color-brown.png', :clas=>"colorimg"%>
		Brown
	</div>
	<div class="checkbox color" id="color-lghtbrown" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="LightBrown" name="Color" value="LTBR" onclick="setProductType('Light Brown')">
		<%= image_tag 'color-light-brown.png', :clas=>"colorimg"%>
		Light Brown
	</div>
	<div class="checkbox color" id="color-auburn" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="Auburn" name="Color" value="AUB" onclick="setProductType('Auburn')">
		<%= image_tag 'color-auburn.png', :clas=>"colorimg"%>
		Auburn
	</div>
	<div class="checkbox color" id="color-blonde" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="Blonde" name="Color" value="BLN" onclick="setProductType('Blonde')">
		<%= image_tag 'color-blonde.png', :clas=>"colorimg"%>
		Blonde
	</div>
	<div class="checkbox color" id="color-lghtblonde" style="margin-top: 0px;padding-left:0px">
		<input type="radio" id="LightBlonde" name="Color" value="LTBLN" onclick="setProductType('Light Blonde')">
		<%= image_tag 'color-light-blonde.png', :clas=>"colorimg"%>
		Light Blonde
	</div>
</div>

app/views/home/_cart.html.erb
<table width="100%" class="table table-bordered">
	<% if session[:cart] && session[:cart].size > 0 %>
		<% session[:cart].each do |c| %>
		<tr>
			<td width="100px"> 
			<b><%= c[:name] %></b></td>
			<td width="50px" style="text-align: center"><b><%= c[:quantity].to_i %></b></td>
			<td width="60px" style="text-align: center"><b><%= number_with_precision(c[:price], :precision => 2) %>$</b></td>
			<td width="50px" style="text-align: center"><%= link_to "X", "", :onclick=>"removeProduct(event,'#{c[:name]}')" %></td>
		</tr>
	<% end %>
	<tr>
		<td colspan="4" style="text-align: right;padding:8px;"> Total Amount: <%= get_total_amount %>$ </td>
	</tr>
	<% else %>
	<tr>
		<td colspan="4" style="text-align: center"> Please select products to checkout. </td>
	</tr>
	<% end %>
</table>
<%= hidden_field_tag "url", :value=>"" %>

app/views/home/_instagram.html.erb
<%= stylesheet_link_tag "theme", media: "all" %>
<section class="index-module instagram-feed">
	<h2 class="index-section-title container"><i class="icon-instagram"></i> Instagram Feed <a target="new" href="https://instagram.com/hairillusionllc/" class="instagram-see-all" style="margin-right: 60px;">See All</a></h2>

	<div class="inner">
		<div id="instafeed">
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3UiYGqSphd/" target="_blank"><div class="overlay"></div><%= image_tag('insta1.jpg') %> </a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3UERAlyptY/" target="_blank"><div class="overlay"></div><%= image_tag('insta2.jpg') %> </a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3PixoESpiP/" target="_blank"><div class="overlay"></div><%= image_tag('insta3.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3PiE7ZSpgs/" target="_blank"><div class="overlay"></div><%= image_tag('insta4.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3NLXEIypp8/" target="_blank"><div class="overlay"></div><%= image_tag('insta5.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3Mq_oVSpu-/" target="_blank"><div class="overlay"></div><%= image_tag('insta6.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3KvIOOyph4/" target="_blank"><div class="overlay"></div><%= image_tag('insta7.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3KnlFUyplI/" target="_blank"><div class="overlay"></div><%= image_tag('insta8.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3KRA49yphK/" target="_blank"><div class="overlay"></div><%= image_tag('insta9.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3HMbmtypp7/" target="_blank"><div class="overlay"></div><%= image_tag('insta10.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/2_48ZpSpvc/" target="_blank"><div class="overlay"></div><%= image_tag('insta11.jpg') %></a>
			</div>
			<div class="picture-wrapper">
				<a href="https://instagram.com/p/3BqHrqSplM/" target="_blank"><div class="overlay"></div><%= image_tag('insta12.jpg') %></a>
			</div>
		</div>
	</div>
</section>

app/views/home/_no_matches.html.erb
<div class="section" style="padding:20px;text-align: center">
	Sorry, There are no forums in searched criteria.
</div>

app/views/home/add_to_cart.js.erb
$("#listTable").html(" <%= escape_javascript( render 'cart') %>");  
$("#buy_url").val('<%=@url%>')
$("#products_size").val('<%=session[:cart].size%>')

app/views/home/after_payment_page.html.erb
<% if params[:payer_status] == "verified" %>

<div style="width: 100%;text-align: center;color:#fff;padding:20px;">

<h4> Thank you for your order.</h4>

<h4> Please check your email for confirmation email.</h4>

<br />
 
<%= link_to "Home", "/", :class=>"ordnwbtn" %>

</div>

<%else %>
  <h3>Something went wrong..Please contact admin if your money deducted.</h3>
<%end %>

app/views/home/clear_all.js.erb
<% if params[:type] == "bonus" %>
	$("#bonusRadio").html(" <%= escape_javascript( render 'bonus_products') %>");       
	$("#cb_country").val('US')  
	$('#cb_country').trigger('change'); 
	$("#billing_country").val('US')  
	$('#billing_country').trigger('change');
	$("#cb_country").hide()
	$("#billing_country").hide() 
	
	$("#countryLabel2").removeClass('hide')
	$("#countryLabel2").show() 
	
	$("#countryLabel1").removeClass('hide')
	$("#countryLabel1").show() 


<%else%>
	$("#bonusRadio").html(" <%= escape_javascript( render 'normal_products') %>");   
	$("#cb_country").show()
	$("#billing_country").show()
	$("#countryLabel2").hide()
	$("#countryLabel1").hide() 
<%end%>

$("#cartTR").html(" <%= escape_javascript( render 'product_cart') %>");    
$("#totalDiv").html(" <%= escape_javascript( render 'total_price') %>");    

app/views/home/customer_login.html.erb
<div style="color:#fff">
	<h4>Login</h4>
	<%= form_for :customer, url: home_login_path, html: { class: 'form-horizontal' }, :remote=>true do |f| %>
	<table style="color:#000">
		<tr>
			<td style="padding: 10px;font-size: 14px;color: #fff">Email:</td>
			<td><%= f.email_field :email %></td>
		</tr>
		<tr>
			<td style="padding: 10px;font-size: 14px;color: #fff">Password:</td>
			<td><%= f.password_field :password%></td>
		</tr>
		<tr>
			<td colspan="2">
				<%= f.submit "Login", :class=>"btn btn-primary btn-sm"%>
			</td>
		</tr>
	</table>
	<%end%>

</div>

app/views/home/forum.html.erb
<div style="background: #fff;padding:30px">
<h5 class="title-text text-center"> <%= link_to "Salons & Barbers post your store location.", new_forum_path, :class=>"btn btn-danger" %> </h5> 
 <br />
<h4 class="title-text text-center">Search for Salons & Barbers in your state who carry Hair Illusion</h4> 
<div class="section" style="border: solid;border-width: 1px;padding: 10px;border-color: #ccc">
	<%= form_for :search, url: get_forums_path, html: { class: 'form-horizontal' }, :remote=>true do |f| %>
	<table>
		<tr>
			<td style="padding: 10px">Country:</td>
			<td style="padding: 10px">
				<%= f.country_select :country,{ :default => 'United States', selected: 'US'}, { class: 'form-control required', :onchange=>"onChangeCounty()" } %></td>
			<td style="padding: 10px">State:</td>
			<td style="padding: 10px" id="state_td">
				<%= render partial: 'subregion_select', locals: {parent_region: 'US' } %>
			</td>
			<td style="padding: 10px"><%= f.submit "Search", :class=>"btn btn-primary"%></td> 
		</tr>
	</table>
	<%end%>
</div>
<ul class="list-group" style="background-color: #eee"> 
	<div id="forumList">
		<%= render "forum_list", :forums=>@forums %> 
	</div>
</ul>
<br />  
</div>
<script type="text/javascript"> 
  $(document).ready(function(){
	$('.ckeditor').ckeditor({ 
	});
  }); 
</script>

app/views/home/get_shipping.js.erb
$('#shipButtton').text("Choose shipping carriers");
$('#shipButtton').prop('disabled', false);
		

<% if @error == '' %>
	$("#shippingDiv").html(" <%= escape_javascript( render 'shipping_methods') %>");  
<%else%>
	alert("<%=@error%>")
<%end%>

app/views/home/how_it_works.html.erb
<%= content_for :jumbotron do %>
  <div class="jumbotron">
    <div class="container">
      <h2 class="text-center">Hair Illusion – How Does It Work?</h2>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <%= image_tag 'ronnie_with_bottle.jpg', class: 'img-responsive', style: 'margin-top:10%' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <h4 class='title-text'>ONLY NATURAL</h4>
  <p>Hair Illusion is virtually undetectable to the naked eye.</p>
  <p>Every time you look in the mirror you will be amazed by the natural look.</p>

  <h4 class='title-text'>SHAKE & APPLY</h4>
  <p>To apply Hair Illusion Simply shake the bottle liberally over thin and bald areas.</p>
  <p>This will release thousands of microscopic color matched fibers, which bond to your scalp or thin hair with magnetized static electricity.</p>

  <h4 class='title-text'>RELAX & ENJOY</h4>
  <p>Hair Illusion won't come off in the wind or with perspiration.</p>
  <p>To remove the product, simply wash out with shampoo.</p>
  <p>For an extra hold apply a light mist hair spray.</p>
</div>

app/views/home/shutdown.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hair Illusion Shutdown</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
  <a class="sr-only" href="#content">Skip to main content</a>
  <header class="navbar navbar-inverse navbar-static-top bs-docs-nav" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to(image_tag('hair-illusion-logo-40.jpg'), root_path, class: "navbar-brand", style: "margin-top: 10px") %>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation" style="height: 1px;">
        <ul class="nav navbar-nav" style="margin-top: 20px">
          <li><%= link_to '&nbsp;'.html_safe, '#' %></li>
        </ul>
      </nav>
    </div>
  </header>

  <div class="container"></div>
</body>
</html>