config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Hairillusion::Application.routes.draw do 
  
  get "users/index"
  get "products/index"
  get "agents/index"
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'
  
  get '/distributors/subregion_options' => 'distributors#subregion_options'
  get '/set_setting_carriers' => 'distributors#set_setting_carriers'
    
  get '/agent' => 'home#portal' 
  post 'home/create_portal_order'
  get '/customer_login' => 'home#customer_login' 
  
  get '/set_shipping_values' => 'home#set_shipping_values'
  get '/get_shipping' => 'home#get_shipping' 
  
  post "home/login"

  get '/get_total_price' => 'distributors#get_total_price' 
  get '/faq' => 'home#faq'
  get '/thankyou' => 'home#thankyou'
  post '/after_payment' => 'home#after_payment'
  post '/save_forum' => 'home#save_forum'
  get '/after_payment' => 'home#after_payment'
  post '/thankyou' => 'home#thankyou'
  post '/create_order' => 'orders#create_order'
  post '/create_agent_order' => 'orders#create_agent_order'
  get '/buy_now' =>"home#buy_now"
  get '/get_agent_form' => "home#get_agent_form"
  post '/after_payment_page' => 'home#after_payment_page'  
  post '/get_forums' => 'home#get_forums' 
  get '/new_forum' => 'home#new_forum' 
  get '/get_states' => 'home#get_states'
  get '/buy_upsell'=> 'orders#buy_upsell'
  get '/next_upsell'=> 'orders#next_upsell' 
  get '/add_to_cart' => 'home#add_to_cart'
  get '/remove_from_cart' => 'home#remove_from_cart'
  get '/add_product_to_cart' => 'home#add_product_to_cart'
  get '/clear_all' => 'home#clear_all'
  
  
  get '/fibre_hold' => 'home#fibre_hold'
  get '/forum' => 'home#forum'
  get '/more_reviews' => 'home#more_reviews'  
  
  get '/terms' => 'home#terms'
  get '/testimonials' => 'home#testimonials'
  get '/photos' => 'home#photos'
  get '/how_it_works' => 'home#how_it_works'
  get '/what_is_it' => 'home#what_is_it'
  get '/about_us' => 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/color' => 'home#color'
  get '/mens_hair_loss' => 'home#mens_hair_loss'
  get '/womens_hair_loss' => 'home#womens_hair_loss'
  get '/forgot_password' => 'home#forgot_password'
  post '/forgot_password_email' => 'home#forgot_password_email'
  get '/password_reset_success' => 'home#password_reset_success'
  get '/show_hide_billing_details' => 'home#show_hide_billing_details'
  post 'users/update_card_details'
  post 'users/logout'
  
  resources :orders, only: [:new, :create, :buy_product] do
    collection do
      get :confirmation
      get :buy_product 
    end
  end 

  
  resources :distributors, only: [:new, :create] do
    collection do 
      get :confirmation
      get :show
      get :edit
      put :update
      post :login
      get :logout
      post :order
      get :past_orders
    end
  end

  resources :health_check, only: [:index]

  namespace :admin do
    resources :country_prices do
      collection do
        post :update_price
      end
    end
    
    resources :agents do 
      collection do 
        get 'get_orders'
        get 'get_orders_xls'
      end
    end 
    
    resources :coupons do 
      collection do 
        get :logout
      end 
    end
     
    get "/" => "orders#index"
    
    resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index, :new, :create]
    end 
    
    resources :forums do
    end   
    
    resources :domain_distributors do
      collection do
        post :filter_report 
        get :download_report 
      end 
    end
    
    resources :products
      
    resources :distributors, except: [:destroy] do
      resources :orders, only: [:index, :new, :create]

      member do
        get :approve
        get :set_price
        post :update_price
      end
      collection do 
        
      end
    end
    
    resources :users
    resources :orders, except: [:destroy]  do
      member do
        put :refund 
        get 'send_invoice'
        get 'release_order'
      end
      collection do
        
        get :refund
        get 'get_orders'
        get 'get_refund' 
        get 'get_refundable_orders'
        get 'change_date'
        get 'update_date'
        get 'update_customer_price'
        get 'update_days_gap'
        get "show_price"
        get "update_price"
        get "cancel_order"
        get "cancel1_order"
        get "cancel_order2"
        get :pull_details_from_shopify 
        get :distributor_orders
        get 'club_orders'
        get 'cancel_orders'
        get 'filter_orders'
        get 'get_orders'
      end
    end

    resources :shipments, except: [:destroy] 
    
    resources :subscribers do
      collection do
        get "download_contacts_csv"
      end
    end
    
  end
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  extend GridTable
  
  has_many :orders, dependent: :nullify 
  grid_table_control :created_at
end

app/controllers/admin/shipments_controller.rb
class Admin::ShipmentsController < Admin::ApplicationController
  respond_to :html
  respond_to :js, only: [:index]
  respond_to :xml, only: [:show]

  def index
    respond_to do |format|
      format.html {}
      format.js do
        @shipments = Shipment.all
        grid_table_for(@shipments, index_params)
      end
    end
  end

  def show
    @shipment = Shipment.find(params[:id])

    respond_to do |format|
      format.html {}
      format.xml { send_data(render_to_string( template: 'admin/shipments/show' ), filename: 'shipment.xml') }
    end
  end

  def create
    @shipment = Shipment.new
    @shipment.orders<< Order.unshipped.order(:created_at)

    @shipment.save

    redirect_to admin_shipment_path(@shipment)
  end

  private
  def index_params
    params.permit [].concat(Shipment.grid_table_strong_params)
  end
end

app/views/admin/shipments/_row.html.erb
<tr>
  <td><%= shipment.created_at %></td>
  <td>
    <%= link_to icon_text('Detail', 'glyphicon glyphicon-info-sign'), admin_shipment_path(shipment), class: 'btn btn-sm btn-success' %>
    <%= link_to icon_text('Download', 'glyphicon glyphicon-cloud-download'), admin_shipment_path(shipment, format: :xml), class: 'btn btn-sm btn-primary' %>
  </td>
</tr>

app/views/admin/shipments/index.html.erb
<h2>Shipments</h2>
<% unshipped_count = Order.unshipped.count %>
<b><%= pluralize(unshipped_count, 'unshipped order') %></b>
<% if unshipped_count > 0 %>
  <%= link_to "New Shipment", admin_shipments_path, method: :post, class: 'btn btn-sm btn-primary' %>
<% end %>

<table class="table table-striped table-bordered table-hover table-condensed grid-table" data-url="<%= admin_shipments_path %>">
  <thead>
    <tr>
      <th data-field="created_at" data-sort="true" data-default-sort="desc">Created</th>
      <th></th>
    </tr>
    <tr class="filters">
      <th class="filter">
        <%= text_field_tag :filter_created_at, nil, 'data-field' => 'created_at' %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody></tbody>
  <tfoot>
    <tr>
      <th colspan="2">
        <%= render 'admin/shared/grid_pager' %>
      </th>
    </tr>
  </tfoot>
</table>

app/views/admin/shipments/show.html.erb
<h2>Shipment - <%= @shipment.created_at %></h2>
<%= link_to(icon_text('Download', 'glyphicon glyphicon-cloud-download'), admin_shipment_path(@shipment, format: :xml), class: 'btn btn-small btn-primary') %>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Created</th>
      <th>Order #</th>
      <th>Ordered By</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @shipment.orders.each do |order| %>
      <tr>
        <td><%= order.created_at %></td>
        <td><%= order.id %></td>
        <td>
          <% if order.orderer_type == Customer.name %>
            <%= link_to("#{order.orderer.first_name} #{order.orderer.last_name}", admin_customer_path(order.orderer)) %>
          <% elsif order.orderer_type == Distributor.name %>
            <%= link_to(order.orderer.company_name, admin_distributor_path(order.orderer)) %>
          <% end %>
        </td>
        <td>
          <%= link_to icon_text('Detail', 'glyphicon glyphicon-info-sign'), admin_order_path(order), class: 'btn btn-sm btn-success' %>
          <%= link_to icon_text('Edit', 'glyphicon glyphicon-pencil'), edit_admin_order_path(order), class: 'btn btn-sm btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>